### PR TITLE
Update to node-netflix v0.1.6

### LINKED ISSUE #35: Cannot export profile because of Error: Invalid URI "undefined/v73fa49e3/profiles"
Hi! I am using the following command
`netflix-migrate --email MYEMAIL@example.com --profile MYPROFILE --export netflixData.json
`

but I get the following error (nom v6.10.0 and tried on both windows, MacOS)

> Error: Invalid URI "undefined/v73fa49e3/profiles"
    at Request.init (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:273:31)
    at new Request (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:127:8)
    at request (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\index.js:53:10)
    at Netflix.__request (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\index.js:100:12)
    at Netflix.__apiRequest (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:297:8)
    at Netflix.getProfiles (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:100:8)
    at internal/util.js:286:30
    at new Promise (<anonymous>)
    at Netflix.getProfiles (internal/util.js:285:12)
    at AsyncFunction.main.getProfileGuid (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\main.js:95:28)
Error: Profile GUID could not be determined. For more information, please see previous logstatements.
    at AsyncFunction.main.getProfileGuid (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\main.js:98:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

### PR DESCRIPTION
**Pull request by LBBO**
Netflix changed their react models again and seem to have removed the shakti API URL. This PR adds it as a constant instead of retrieving it from react.

Should fix #35

### CODE REVIEW

**Comment by pnmcosta** [comment]
Hello,

Just came across your project and am in need of this to migrate my profile to a new account, do you plan on merging this PR?

I'll pick #32 up, but no promises, just not sure if I need this PR or not for it.

Thanks,
P.

**Comment by pnmcosta** [comment]
Nevemind, I figured out what's happening, I'll work on a PR for node-netflix2 instead. It seems straight forward it uses `/pathEvaluator` to get the list contents.

**Comment by LBBO** [comment]
Sorry, I had already published this branch (see e2df66a) but then forgot to merge it. And thanks for your help with node-netflix2, I really appreciate it!

**Comment by pnmcosta** [comment]
Kewl, no worries, I've made some progress, have a successfull skeleton for the request, however it's not working, and having some debugging issues that I need to overcome.

I'll be pushing a feature branch to my fork soon, but non workin WIP for the moment.

**Pull request merged**
