### PR TITLE
Move project to LBBO/netflix-migrate

### PR DESCRIPTION
**Pull request by genderquery**
Since I haven't had the interest in maintaining this project and @LBBO has done a great job as a contributor, I figure it's time to make it official and hand it off to them.

@LBBO, approve this PR if you want the project and feel free to do what you will with it.

### CODE REVIEW

**Comment by Stanzilla** [comment]
why not transfer the repo? GitHub allows that.

**Comment by LBBO** [comment]
I agree with @Stanzilla. Transferring has a lot of advantages listed [https://help.github.com/en/articles/transferring-a-repository#whats-transferred-with-a-repository](here).

@genderquery Please let me know wether you agree so I can clean up and delete my forks of both this project and node-netflix2. Otherwise, we could do it this way.

Aside from the repository though: does anything need to be done on npm? I don't think so, but I don't know my way around npm too well and I'd just like to make sure.

**Comment by genderquery** [comment]
Sure, I can transfer it, I've just never done it before. According to the documentation, you can't have a fork with the same name, so maybe rename yours (as opposed to deleting it) in case something goes wrong.

I think the only thing else that would need to be done after the transfer is update the `url` and `homepage` in `package.json` and https://www.npmjs.com/ should pick that up on the next upload.

Let me know if that sounds good and I'll initiate the transfers.

**Comment by LBBO** [comment]
Renaming it sounds great, I'll get to it right now.

**Comment by LBBO** [comment]
Okay, it looks like I will need to delete the forks after all, as I can't have any forks of the original repository and it seems like I can't convert my fork to a normal repository. Any thoughts on workarounds or should I just go ahead and delete it?

**Comment by genderquery** [comment]
I guess there's not much harm in deleting it as long as you got a local working copy of your forks. If you wanted to be extra sure, you could push them into new, differently-named repos on your account before deleting the forks.

**Comment by LBBO** [comment]
Okay, I just deleted my forks. Ready for the transfer when you are.

**Comment by genderquery** [comment]
Transfer initiated. Awaiting approval.

**Comment by LBBO** [comment]
Done. I'll update the package.json and README tomorrow morning, unless you (or someone else) would like to take care of that.

**Pull request merged**
