### PR TITLE
Added YouTube Demo

### PR DESCRIPTION
**Pull request by anjumrafidofficial**
Many people visit this repo but don't know the proper way to use it. To help them & import-export within just 5 minutes added a little demo for newbies.

### CODE REVIEW

**Comment by LBBO** [comment]
Hey @anjumrafidofficial,

adding a demo video is an awesome idea! You're totally right that the documentation isn't sufficient for people who are new to npm and Node.js. Also, thank you so much for putting in the work to make this video!

However, there are a few problems I see so far. First of all, your instructions include some unnecessary steps. To my knowledge, `npx` is automatically installed with Node and NPM, so there is no need to run `npm install -g npx`. The `npm install -g npm@latest` command isn't absolutely necessary, either -- `netflix-migrate` will run even with slightly outdated versions of npm.

The `npm install -g netflix-migrate` command can be skipped as well if you use `npx netflix-migrate ...` later on. `npx` automatically downloads the package to a temporary folder and then executes the command all in one, which is very useful in this case.

Thus, I would recommend reducing the installation instructions to the following:

1. Download and install Node.js from https://nodejs.org/en/download/ . If you don't now which version to choose, choose LTS (**L**ong-**T**erm **S**upport).
2. Open PowerShell (or Terminal, if you're on macOS or Linux)
3. (Optional: update `npm` (was installed alongside Node.js) to latest version `npm install npm@latest -g`)
4. `npx netflix-migrate --email old@example.com --profile "Old profile name" --export netflixData.json`
5. Enter your old Netflix account password
6. Wait for your profile information to be downloaded
7. `npx netflix-migrate --email new@example.com --profile "New profile name" --import netflixData.json`
8. Enter your new Netflix account passoword
8. Boom it's done

I also think it would be a good idea to perhaps include these steps in the README so people aren't forced to search through the video description just to find the commands. Speaking of the README: I'd change the link text to something slightly more inviting, such as "In case you're not so tech savvy, here's a short demo video". I just want to make sure nobody feels offended by the term "newbie" 😉.

Would it be possible for you to re-record the tutorial with these new instructions? If not, I'd be happy to do it myself.

And one last thing: it's very kind of you to include credits to me in the video description, but I'm afraid I can't take all the credit. This is an open source project with many awesome contributors and excluding them wouldn't be fair towards them. The credits are a really nice gesture, but considering there might be even more contributors in the future, I would suggest you just remove the line from the video description.

The two notes about the viewing history and contributing to the project are awesome, though! Thanks for adding them!

Please don't take my feedback in a negative way! I really like your idea and I'm thankful for the work you've already put in. I would just like to make the instructions as short and simple as possible for future users. Next time you have a cool contribution idea, I recommend opening a short issue to check in with the repository maintainers before you put in any work. That way, they can give you their feedback beforehand and you can spend your time as efficiently as possible.

**Comment by anjumrafidofficial** [comment]
yeah sure I'll do it.

**Review by anjumrafidofficial — COMMENTED** [review]
Added New YouTube Video For This Project

**Comment by anjumrafidofficial** [comment]
Thanks for your help @LBBO I've done that so the video time decrease. Also, I've intentionally shown them in notepad so that people don't get confused to think what they need to enter in their session. They can easily compare when they need to know. Also, I don't think this is a confusing matter because the video description also mentioned what they need to enter again in your repo too. If anyone doesn't understand this then I don't think they can use this CLI tool anyway.

**Comment by LBBO** [comment]
Of course the correct commands are given in the notepad, the video description and the repository, but official documentation should never contradict itself. This video, however, directly contradicts the instructions because the commands are different. I know from experience how annoying it is to see two different sets of instructions in virtually the same piece of documentation and then having to figure out on my own which command is correct.

If re-recording the PowerShell part of the video is too much effort for you, I'd be happy to take over the task; just let me know. Sorry for being so nit-picky about this, but I have suffered too much from confusing documentation to knowingly put other people through the same hassle.

**Comment by anjumrafidofficial** [comment]
Can you tell me exactly where should I change it?

**Comment by LBBO** [comment]
Just in the parts of the video that show the PowerShell. You execute the command `netflix-migrate ...` instead of `npx netflix-migrate ...` which is inconsistent with the instructions.

**Review by anjumrafidofficial — COMMENTED** [review]
YouTube Latest Demo Added !!

**Comment by LBBO** [comment]
Hey @anjumrafidofficial,

I'm afraid you used the wrong commands this time (consistently, though, in both the video and the notepad instructions). Those commands **neither** include the `npm install -g netflix-migrate` **nor** the `npx` before the command execution. They work on your machine because you have already installed `netflix-migrate` globally, but they won't work for new users.

Please make sure the video contains the `npx netflix-migrate ...` commands, both in the instructions and in the PowerShell clips.

**Review by anjumrafidofficial — COMMENTED** [review]
YouTube 30 April Video Added !!

**Comment by LBBO** [comment]
Yes, awesome! Thank you so much for your work, this is great!

**Pull request merged**
